<img style="float: left; margin: 30px 15px 15px 15px;" src="https://pngimage.net/wp-content/uploads/2018/06/logo-iteso-png-5.png" width="300" height="500" /> 
    
    
### <font color='navy'> Simulación de procesos financieros. 

**Nombres:** Diego Alberto López Lazareno, Gerardo González Flores.

**Fecha:** 9 de septiembre del 2021.

**Expediente** : IF722100, IF721430.
**Profesor:** Oscar David Jaramillo Zuluaga.
    
**Link Github**: https://github.com/diegolazareno/Tarea2A_DALopez_GGonzalez

# Tarea 2A: Clase 4

## Enunciado de tarea

1. Imagine una rutina contable utilizada en una librería. Funciona en una lista con sublistas, que se ven así:
![imagen.png](attachment:imagen.png)
Escriba un programa en Python, que devuelve una lista con tuplas de tamaño 2. Cada tupla consiste en el número de pedido y el costo total del pedido. El producto debe aumentarse en 10€ si el valor de la orden es inferior a 100,00 €. 
Escribe un programa Python usando unicamente las funciones **lambda y map**.

`orders = [ ["34587", "Learning Python, Mark Lutz", 4, 40.95], 
           ["98762", "Programming Python, Mark Lutz", 5, 56.80], 
           ["77226", "Head First Python, Paul Barry", 3,32.95],
           ["88112", "Einführung in Python3, Bernd Klein", 3, 24.99]]`
           
2. La misma librería, pero esta vez trabajamos en una lista diferente. Las sublistas de nuestras listas se ven así: 
[número de orden, (número de artículo, cantidad, precio por unidad), ... (número de artículo, cantidad, precio por unidad)] 

`orders = [[1, ("5464", 4, 9.99), ("8274",18,12.99), ("9744", 9, 44.95)], 
	       [2, ("5464", 9, 9.99), ("9744", 9, 44.95)],
	       [3, ("5464", 9, 9.99), ("88112", 11, 24.99)],
           [4, ("8732", 7, 11.99), ("7733",11,18.99), ("88112", 5, 39.95)] ]`

Escriba un programa que devuelva una lista de dos tuplas que tengan la información de (número de pedido, cantidad total de pedido). Utilice la función `Reduce`. Recuerde el precio del pedido del producto debe aumentarse en 10€ si el valor de la orden es inferior a 100,00 €.

3. Resolver los anteriores ejercicios usando pandas (DataFrame)

4. Use filter to eliminate all words that are shorter than 4 letters from a list of words
`list='the notion of a lambda function goes all the way back to the origin of computer science'`

5. Use filter to determine the percentage of Fahrenheit temperatures in a list are within the range 32 to 80

6. Use reduce to find the lower left corner (minimum x and minimum y value) for a list of point locations
> **Hint**: Explore the command `np.minimum.reduce` [link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ufunc.reduce.html)

### Ejercicio 1. 

Escriba un programa en Python, que devuelve una lista con tuplas de tamaño 2. Cada tupla consiste en el número de pedido y el costo total del pedido. El producto debe aumentarse en 10€ si el valor de la orden es inferior a 100,00 €. 
Escribe un programa Python usando unicamente las funciones **lambda y map**.

`orders = [ ["34587", "Learning Python, Mark Lutz", 4, 40.95], 
           ["98762", "Programming Python, Mark Lutz", 5, 56.80], 
           ["77226", "Head First Python, Paul Barry", 3,32.95],
           ["88112", "Einführung in Python3, Bernd Klein", 3, 24.99]]`
           

#### Código Diego

In [1]:
# Código de solución
orders = [ ["34587", "Learning Python, Mark Lutz", 4, 40.95], 
           ["98762", "Programming Python, Mark Lutz", 5, 56.80], 
           ["77226", "Head First Python, Paul Barry", 3,32.95],
           ["88112", "Einführung in Python3, Bernd Klein", 3, 24.99]]

accountingBookStore1 = list(map(lambda order : (order[0], order[2] * order[3] if order[2] * order[3] >= 100 
                                                else order[2] * order[3] + 10), orders))
accountingBookStore1

[('34587', 163.8),
 ('98762', 284.0),
 ('77226', 108.85000000000001),
 ('88112', 84.97)]

Para la resolución de este primer ejercicio se hace uso de la función `map` para ir iterando sobre las órdenes contenidas en la lista. Lo que se busca es calcular el costo total de cada pedido considerando la condición de que si éste no supera los $99$ euros entonces se cobrarán $10$ euros adicionales (de lo contrario no se añade ningún costo extra); esto se logra a través del uso de los operadores condicionales `if` y `else`. Además, cabe resaltar que la función anónima `lambda` ayuda a aplicar lo anteriormente mencionado a cada orden durante la ejecución del ciclo. Finalmente se devuelve, por cada iteración, una tupla con el número del pedido y el costo total que se encontrará almacenada en la lista con las demás tuplas. 

#### Código Gerardo

In [1]:
# Código de solución
orders1 = [ ["34587", "Learning Python, Mark Lutz", 4, 40.95], 
           ["98762", "Programming Python, Mark Lutz", 5, 56.80], 
           ["77226", "Head First Python, Paul Barry", 3,32.95],
           ["88112", "Einführung in Python3, Bernd Klein", 3, 24.99]]

# El resultado debe ser como muestro en el resultado de esta celda


list(map(lambda pedido: (pedido[0] ,pedido[2]*pedido[3] if pedido[2]* pedido[3]>=100 else pedido[2]*pedido[3] + 10 ) , orders1))



[('34587', 163.8),
 ('98762', 284.0),
 ('77226', 108.85000000000001),
 ('88112', 84.97)]

### Ejercicio 2. 

La misma librería, pero esta vez trabajamos en una lista diferente. Las sublistas de nuestras listas se ven así: 
[número de orden, (número de artículo, cantidad, precio por unidad), ... (número de artículo, cantidad, precio por unidad)] 

`orders = [[1, ("5464", 4, 9.99), ("8274",18,12.99), ("9744", 9, 44.95)], 
	       [2, ("5464", 9, 9.99), ("9744", 9, 44.95)],
	       [3, ("5464", 9, 9.99), ("88112", 11, 24.99)],
           [4, ("8732", 7, 11.99), ("7733",11,18.99), ("88112", 5, 39.95)] ]`

Escriba un programa que devuelva una lista de dos tuplas que tengan la información de (número de pedido, cantidad total de pedido). Utilice la función `Reduce`. Recuerde el precio del pedido del producto debe aumentarse en 10€ si el valor de la orden es inferior a 100,00 €.

#### Código Diego

In [2]:
# Código de solución
from functools import reduce

orders = [[1, ("5464", 4, 9.99), ("8274",18,12.99), ("9744", 9, 44.95)], 
           [2, ("5464", 9, 9.99), ("9744", 9, 44.95)],
           [3, ("5464", 9, 9.99), ("88112", 11, 24.99)],
           [4, ("8732", 7, 11.99), ("7733",11,18.99), ("88112", 5, 39.95)] ]

accountingBookStore2 = list(map(lambda order : 
                                (order[0], reduce(lambda cost1, cost2 : cost1 + cost2, 
                                list(map(lambda x : x[1] * x[2] if x[1] * x[2] >= 100 
                                else x[1] * x[2] + 10, order[1:])))), orders))
accountingBookStore2

[(1, 688.3299999999999),
 (2, 504.46000000000004),
 (3, 374.79999999999995),
 (4, 502.57)]

La resolución de este ejercicio sigue una lógica similar a la del anterior sólo que aquí será necesario hacer uso de dos `map` y el `reduce`. Primeramente el map exterior itera sobre los distintos números de orden contenidos en la lista, a continuación el `map` interno itera sobre las distintas órdenes hechas por el mismo cliente aplicando el condicional que ya conocemos para calcular el costo total de cada una. Finalmente la función `reduce` nos ayuda a sumar el costo de los pedidos hechos por el mismo número de orden (mismo cliente). El resultado es la lista que imprime la celda de arriba con las tuplas que incluyen la información solicitada: en la primera posicion el número de orden y en la segunda el costo total. 

#### Código Gerardo

In [2]:
# Código de solución
from functools import reduce
########### Solución 2
orders2 = [[1, ("5464", 4, 9.99), ("8274",18,12.99), ("9744", 9, 44.95)], 
          [2, ("5464", 9, 9.99), ("9744", 9, 44.95)],
          [3, ("5464", 9, 9.99), ("88112", 11, 24.99)],
          [4, ("8732", 7, 11.99), ("7733",11,18.99), ("88112", 5, 39.95)] ]

tot = lambda o:  o[-1]*o[-2] if (o[-1]*o[-2] > 101) else (o[-1]*o[-2])+10
prod = lambda a,b: a+b
r = [[tot(orders2[i][j]) for j in range(1,len(orders2[i]))] for i in range(len(orders2))]
result = [[orders2[i][0],reduce(prod,r[i])]for i in range(len(orders2))]
result

[[1, 688.3299999999999],
 [2, 504.46000000000004],
 [3, 374.79999999999995],
 [4, 502.57]]

### Ejercicio 3. 

Resolver los anteriores ejercicios usando pandas (DataFrame).

#### Código Diego

In [3]:
# Código de solución
import pandas as pd

cols = ["Book Order", "Book Title and Author", "Quantity", "Price per Item"]
orders1DF = pd.DataFrame([ ["34587", "Learning Python, Mark Lutz", 4, 40.95], 
           ["98762", "Programming Python, Mark Lutz", 5, 56.80], 
           ["77226", "Head First Python, Paul Barry", 3,32.95],
           ["88112", "Einführung in Python3, Bernd Klein", 3, 24.99]], columns = cols)

orders1DF

Book Order               Book Title and Author  Quantity  Price per Item
0      34587          Learning Python, Mark Lutz         4           40.95
1      98762       Programming Python, Mark Lutz         5           56.80
2      77226       Head First Python, Paul Barry         3           32.95
3      88112  Einführung in Python3, Bernd Klein         3           24.99

In [4]:
accountingBookStoreDF1 = list(map(lambda i : (orders1DF.iloc[i, 0], orders1DF.iloc[i, 2] * orders1DF.iloc[i, 3] 
                                             if orders1DF.iloc[i, 2] * orders1DF.iloc[i, 3] >= 100 
                                             else orders1DF.iloc[i, 2] * orders1DF.iloc[i, 3] + 10), range(len(orders1DF))))
accountingBookStoreDF1

[('34587', 163.8),
 ('98762', 284.0),
 ('77226', 108.85000000000001),
 ('88112', 84.97)]

In [5]:
import pandas as pd
import numpy as np

orders2DF = pd.DataFrame([[1, ("5464", 4, 9.99), ("8274",18,12.99), ("9744", 9, 44.95)], 
           [2, ("5464", 9, 9.99), ("9744", 9, 44.95)],
           [3, ("5464", 9, 9.99), ("88112", 11, 24.99)],
           [4, ("8732", 7, 11.99), ("7733",11,18.99), ("88112", 5, 39.95)]])

orders2DF.drop(0, inplace = True, axis = 1)
orders2DF.fillna("X", inplace = True)
orders2DF

1                   2                  3
0   (5464, 4, 9.99)   (8274, 18, 12.99)   (9744, 9, 44.95)
1   (5464, 9, 9.99)    (9744, 9, 44.95)                  X
2   (5464, 9, 9.99)  (88112, 11, 24.99)                  X
3  (8732, 7, 11.99)   (7733, 11, 18.99)  (88112, 5, 39.95)

In [6]:
accountingBookStoreDF2 = list(map(lambda i : (orders2DF.index[i], 
                            reduce(lambda x, y : x + y, list(map(lambda order : order[1] * order[2] 
                            if order[1] * order[2] >= 100 else order[1] * order[2] + 10, 
                            list(orders2DF.iloc[i,:-1]) if "X" in list(orders2DF.iloc[i,:]) else list(orders2DF.iloc[i,:]))))), 
                            range(len(orders2DF))))

accountingBookStoreDF2

[(0, 688.3299999999999),
 (1, 504.46000000000004),
 (2, 374.79999999999995),
 (3, 502.57)]

1. Para la resolución del primer ejercicio utilizando `Pandas` simplemente se toma el arreglo bidimensional y se convierte a formato *dataframe*. El resto del proceso es similar a la resolución del ejercicio original sólo que aquí para acceder a la información almacenada se emplea el método *.iloc*. El resultado es la lista con las tuplas que contienen el número del pedido y el costo total del mismo.
2. Para la resolución del segundo ejercicio utilizando `Pandas` igualmente se toma el arreglo bidimensional y se convierte a formato *dataframe*. El reto de este ejercicio es que no todos los cientes hicieron $3$ órdenes, por lo que hay casillas vacías. Para arreglar esta situación se propone que el `map` interno itere sobre la fila completa si es que no existe una posición marcada con la *X* (que no contiene información), de lo contrario sólo itera sobre la misma lista pero recortando la posición vacia. A partir de este punto la resolución del problema es similar al ejercicio original y la celda muestra el mismo resultado: la lista que incluye a las tuplas con el número de orden y el costo total de la misma.

#### Código Gerardo

In [3]:
# Código de solución
#Ejercicio 1
# Código de solución
import pandas as pd

cols = ["Book Order", "Book Title and Author", "Quantity", "Price per Item"]
orders1DF = pd.DataFrame([ ["34587", "Learning Python, Mark Lutz", 4, 40.95], 
           ["98762", "Programming Python, Mark Lutz", 5, 56.80], 
           ["77226", "Head First Python, Paul Barry", 3,32.95],
           ["88112", "Einführung in Python3, Bernd Klein", 3, 24.99]], columns = cols)

orders1DF

Book Order               Book Title and Author  Quantity  Price per Item
0      34587          Learning Python, Mark Lutz         4           40.95
1      98762       Programming Python, Mark Lutz         5           56.80
2      77226       Head First Python, Paul Barry         3           32.95
3      88112  Einführung in Python3, Bernd Klein         3           24.99

In [4]:
accountingBookStoreDF1 = list(map(lambda i : (orders1DF.iloc[i, 0], orders1DF.iloc[i, 2] * orders1DF.iloc[i, 3] 
                                             if orders1DF.iloc[i, 2] * orders1DF.iloc[i, 3] >= 100 
                                             else orders1DF.iloc[i, 2] * orders1DF.iloc[i, 3] + 10), range(len(orders1DF))))
accountingBookStoreDF1

[('34587', 163.8),
 ('98762', 284.0),
 ('77226', 108.85000000000001),
 ('88112', 84.97)]

In [5]:

#Ejercicio 2
import pandas as pd
import numpy as np

orders2DF = pd.DataFrame([[1, ("5464", 4, 9.99), ("8274",18,12.99), ("9744", 9, 44.95)], 
           [2, ("5464", 9, 9.99), ("9744", 9, 44.95)],
           [3, ("5464", 9, 9.99), ("88112", 11, 24.99)],
           [4, ("8732", 7, 11.99), ("7733",11,18.99), ("88112", 5, 39.95)]])

orders2DF.drop(0, inplace = True, axis = 1)
orders2DF.fillna("X", inplace = True)
orders2DF

1                   2                  3
0   (5464, 4, 9.99)   (8274, 18, 12.99)   (9744, 9, 44.95)
1   (5464, 9, 9.99)    (9744, 9, 44.95)                  X
2   (5464, 9, 9.99)  (88112, 11, 24.99)                  X
3  (8732, 7, 11.99)   (7733, 11, 18.99)  (88112, 5, 39.95)

In [6]:
accountingBookStoreDF2 = list(map(lambda i : (orders2DF.index[i], 
                            reduce(lambda x, y : x + y, list(map(lambda order : order[1] * order[2] 
                            if order[1] * order[2] >= 100 else order[1] * order[2] + 10, 
                            list(orders2DF.iloc[i,:-1]) if "X" in list(orders2DF.iloc[i,:]) else list(orders2DF.iloc[i,:]))))), 
                            range(len(orders2DF))))

accountingBookStoreDF2

[(0, 688.3299999999999),
 (1, 504.46000000000004),
 (2, 374.79999999999995),
 (3, 502.57)]

### Ejercicio 4. 

Use filter to eliminate all words that are shorter than 4 letters from a list of words
`list='the notion of a lambda function goes all the way back to the origin of computer science'`.

#### Código Diego

In [7]:
# Código de solución
list1 = 'the notion of a lambda function goes all the way back to the origin of computer science'

filteredList = list(filter(lambda element : len(element) >= 4, list1.split()))
filteredList

['notion',
 'lambda',
 'function',
 'goes',
 'back',
 'origin',
 'computer',
 'science']

La resolución de este ejercicio arroja la lista anterior que contiene las palabras de la frase que tienen $4$ o más letras. En código simplemente se aplicó la función `filter` que permite iterar sobre un conjunto de elementos para filtrar aquellos que cumplan cierta condición, en este caso con ayuda de la función anónima se pudo aplicar el condicional para que cada palabra traída tuviese una longitud mayor o igual a $4$. Un elemento importante para la resolución de este problema es que debe emplearse la función `split` sobre la lista original para que nos devuelva a las palabras por separado o como elementos de un objeto iterable.

#### Código Gerardo

In [7]:
# Código de solución
lista='the notion of a lambda function goes all the way back to the origin of computer science'
lista.split()

list(filter(lambda x: len(x)>=4 , lista.split()))

['notion',
 'lambda',
 'function',
 'goes',
 'back',
 'origin',
 'computer',
 'science']

### Ejercicio 5. 

Use filter to determine the percentage of Fahrenheit temperatures in a list are within the range 32 to 80.

#### Código Diego

In [8]:
# Código de solución
import numpy as np
np.random.seed(55555)
temperatures = np.random.uniform(25,110,30)

percentage = len(list(filter(lambda temp : (temp >= 32) & (temp <= 80), temperatures))) / len(temperatures)
percentage

0.4666666666666667

Al igual que en el ejercicio anterior se empleó a la función `filter` para iterar sobre la lista de temperaturas y filtrar, con ayuda de la función `lambda`, a aquellas que se encuentran dentro del rango de $32$ y $80$. Una vez que se tiene esta lista con las temperaturas filtradas es fácil conocer el porcentaje que cumple con el condicional, para ello se toma la longitud de dicho conjunto filtrado y se divide por la longitud del conjunto original, de esta forma se puede saber, como ya se mencionó, el porcentaje de temperaturas dentro del rango: en este caso es el $46 \%$.

#### Código Gerardo

In [8]:
# Código de solución
import numpy as np
np.random.seed(55555)
temperatures = np.random.uniform(25,110,30)
print(temperatures)

porcentaje=len(list(filter(lambda temperatura: 32<=temperatura<=80 , temperatures)))/len(temperatures)
porcentaje

[ 35.97387961  99.13294268  92.6178302   99.69549478  63.21119535
  73.90387697  95.50028838  99.21476553  36.98251238 101.45813729
 100.5917418   89.38159435  89.52156589  83.8084752   28.37990868
  68.75395211  45.86132067  36.58307493  56.32208365  33.96219302
  45.29071318  74.86289938  66.51091383  88.19316186  94.26635864
  46.83131624 109.60744472 109.68427993  44.55796499  92.84146259]


0.4666666666666667

### Ejercicio 6. 

Use reduce to find the lower left corner (minimum x and minimum y value) for a list of point locations.
> **Hint**: Explore the command `np.minimum.reduce` [link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ufunc.reduce.html)

#### Código Diego

In [9]:
# Código de solución
np.random.seed(55555)
point_xy = np.random.randint(0,100,[30,2])

print("Usando el módulo de numpy : ")
minimuns1 = np.minimum.reduce(point_xy, axis = 0)
minimuns1

Usando el módulo de numpy : 


array([0, 2])

In [10]:
print("Usando map y lambda : ")
minimuns2 = np.array(list(map(lambda i : min(list(map(lambda row : row[i], point_xy))), range(len(point_xy[0])))))
minimuns2

Usando map y lambda : 


array([0, 2])

Con ayuda de la función `minimum.reduce` de la librería *numpy* (configurada en *axis = 0*) pueden obtenerse en un arreglo los valores mínimos de cada columna de una matriz: en este caso $0$ (primer columna) y $2$ (segunda columna). Además traté de desvelar la manera en que opera este módulo con ayuda de las funciones `map` y `lamba` que hemos estado viendo en clase. El problema puede resolverse fácilmente si con `map` iteramos sobre el número de columnas para traer en una lista (con ayuda de otro `map`) a todos los elementos de cada columna con el fin de obtener su valor mínimo (que será almacenado en la lista del `map` externo).

#### Código Gerardo

In [9]:
# Código de solución
np.random.seed(55555)
point_xy = np.random.randint(0,100,[30,2])
print(point_xy)

[[17 97]
 [22 33]
 [37 46]
 [57 28]
 [11 25]
 [14  2]
 [74 16]
 [12 37]
 [35 21]
 [66 65]
 [86 58]
 [67 81]
 [ 0 48]
 [28 66]
 [76 22]
 [46 47]
 [64  7]
 [88 94]
 [65 13]
 [75 89]
 [23 17]
 [36 63]
 [62 36]
 [64 17]
 [18 19]
 [88 41]
 [21 49]
 [98 36]
 [81 73]
 [62 90]]


In [10]:
# Respuesta
np.minimum.reduce(point_xy)

array([0, 2])